name: Compile and run unit tests

on:
  push:
    branches-ignore:
      - main

jobs:
  compile-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile and test using Maven
      run: mvn --batch-mode --update-snapshots verify
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}