name: Compile, run unit tests and publish package to Github Packages

on:
  push:
    branches:
      - main

jobs:
  compile-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Prepare environment
      uses: ./.github/workflows/prepare-env.yml
    - name: Run maven deploy
      uses: ./.github/workflows/maven.yml
      with:
        maven-command-attributes: deploy
        token: ${{ secrets.GITHUB_TOKEN }}

#    uses: ./.github/workflows/maven.yml
#    with:
#      maven-command-attributes: deploy
#    permissions:
#      contents: read
#      packages: write
#    secrets:
#      token: ${{ secrets.GITHUB_TOKEN }}