name: Compile, run unit tests and publish package to Github Packages

on:
  push:
    branches:
      - main

jobs:
  compile-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Prepare environment
      uses: ./.github/actions/prepare-env
    - name: Run maven deploy
      uses: ./.github/actions/execute-maven-command
      with:
        maven-command-attributes: deploy
        token: ${{ secrets.GITHUB_TOKEN }}