name: Compile and run unit tests

on:
  push:
    branches-ignore:
      - main

jobs:
  compile-test:
    uses: ./.github/workflows/maven-workflow.yml
    with:
      maven-command-attributes: verify
    permissions:
      contents: read
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}