name: Compile, run unit tests and publish package to Github Packages

on:
  push:
    branches:
      - main

jobs:
  compile-test-publish:
    uses: ./.github/workflows/maven-workflow.yml
    with:
      maven-command-attributes: deploy
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}