name: Compile, run unit tests and publish package to Github Packages

on:
  release:
    types: created

jobs:
  set-pom-version-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Update version in pom.xml
        run: mvn --batch-mode versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

  compile-test-publish:
    needs: set-pom-version-from-tag
    uses: ./.github/workflows/maven-workflow.yml
    with:
      maven-command-attributes: deploy
    permissions:
      contents: read
      packages: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}